name: qr_code_generator
description: A Flutter app to generate QR codes from text input.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^10.4.3
  provider: ^6.0.5
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
